name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build_images:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    strategy:
      fail-fast: false
      matrix:
        os: ["debian","alpine"]
        php: ["8.0"]
        dockerfile: ["base", "octane", "puppeteer", "octane,puppeteer"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
              ./build.sh -p ${{ matrix.php }} -o ${{ matrix.os }} -s ${{ matrix.dockerfile }} --publish